apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alessandrocaglio/argocd-gitops.git'
    path: infrastructure/apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true