# apiVersion: v1
# kind: Namespace
# metadata:
#   name: istio-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sail-operator
  namespace: olm # Or a dedicated istio-operator namespace
spec:
  channel: stable
  name: sail-operator
  source: operatorhubio-catalog
  sourceNamespace: olm