apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/alessandrocaglio/argocd-gitops.git'
    path: infrastructure/operators/olm/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: olm
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]